# Generated by Django 5.2.6 on 2025-11-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter_analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="party_affiliation",
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name="voter",
            name="precinct_number",
            field=models.CharField(max_length=2),
        ),
    ]
