# Generated by Django 5.2.6 on 2025-09-25 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_insta", "0002_alter_profile_bio_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="join_date",
            field=models.DateTimeField(blank=True),
        ),
    ]
