# Generated by Django 5.2.6 on 2025-09-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_insta", "0003_alter_profile_join_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile", name="join_date", field=models.DateField(blank=True),
        ),
    ]
