# Generated by Django 5.2.6 on 2025-10-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_insta", "0005_post_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post", name="caption", field=models.TextField(),
        ),
    ]
