# Generated by Django 5.2.6 on 2025-10-16 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_insta", "0007_photo_image_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile", name="display_name", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="profile", name="join_date", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="profile", name="profile_image_url", field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="profile", name="username", field=models.TextField(),
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "follower_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follower_profile",
                        to="mini_insta.profile",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="mini_insta.profile",
                    ),
                ),
            ],
        ),
    ]
