# Generated by Django 5.2.6 on 2025-10-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_insta", "0010_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="join_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
