# Generated by Django 5.2.6 on 2025-12-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="class", name="name", field=models.TextField(blank=True),
        ),
    ]
