# Generated by Django 5.2.6 on 2025-12-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_class_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile", name="discussion", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="profile", name="lecture", field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="class", name="name", field=models.TextField(),
        ),
    ]
