# Generated by Django 5.2.6 on 2025-12-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_profile_discussion_profile_lecture_alter_class_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="class", name="question",),
        migrations.AlterField(
            model_name="profile", name="discussion", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="profile", name="lecture", field=models.TextField(),
        ),
    ]
