# Generated by Django 5.2.6 on 2025-12-08 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_remove_class_question_alter_profile_discussion_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="class", name="classroom",),
    ]
