# Generated by Django 5.2.6 on 2025-12-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="appeal",
            name="status",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile", name="discussion", field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="profile", name="lecture", field=models.TextField(blank=True),
        ),
    ]
