# Generated by Django 5.2.6 on 2025-12-09 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0007_appeal_status_alter_profile_discussion_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="email",),
    ]
