# Generated by Django 5.2.6 on 2025-12-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0008_remove_profile_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="attend",
            name="status",
            field=models.TextField(default="attended"),
            preserve_default=False,
        ),
    ]
